### ISSUE TITLE
Update paired project 2

### ISSUE THREAD

**Issue by wvmitchell** [turingschool/front-end-curriculum#582]
# Project to be updated: [Rom Com](https://frontend.turing.edu/projects/module-1/romcom-pair-v2.html)

## Summary of changes needed: 
- The project currently pushes students to make use of a Cover class, this should be replaced with some guidance on how to store the information about a cover in an object literal
- Reference to using the Cover class should likewise be updated
- The boilerplate Cover class should be removed from the starter repo
- All group projects should make clear that a failure to participate can result in an individual failing the project, even if the project is otherwise passing

**Comment by hfaerber** [comment]
PR for starter-repo updates - [here](https://github.com/turingschool-examples/romcom/pull/324)

PR for project spec - [here](https://github.com/turingschool/front-end-curriculum/pull/652)

**Comment by hfaerber** [comment]
Updating this brought up questions about the updates to the other paired project Hang In There:  

1) That spec states `* All of your JavaScript will be written in `domUpdates.js` - you will not need to change any other files.`
There is no domUpdates.js file in the starter kit.  Students will need to update both files, not just the dom file.  Maybe we can also update the readme in the starter kit to help students understand what is expected in each file.
*^^I'm in the process of updating this in both the spec and the file structure of the boilerplate repo.  Confirming with M1 team how we want this set up*

2) The spec states as a WOW for functional programming competencies `- Creating effective, clean methods in the provided createPoster function to manipulate object properties`. They won't be creating methods within that function.   
*^^I ended up deleting this line altogether and put the function purity note in under that section instead of having it in the JS section*

**Comment by CassandraGoose** [comment]
I'm looking at this PR now - as long as the boilerplate README and the spec aren't contradicting each other, then I vote for just having the information in one spot. That way, if it ever changes, it only has to be changed in one spot. I've noticed that in general, we don't update things when updates are required in multiple areas and then we end up in situations where there are two totally different sets of instructions, which is more confusing for students. 

I'm only one vote, though! I trust you and if you want to update the boilerplate README - go for it! 💪

**Comment by hfaerber** [comment]
Thanks so much Cass!  I removed the file structure outline from the README since its already noted in the spec (and as comments in the files themselves).  Good call out!
